In [1]:
import numpy as np

# 1. Create a null vector of size 10 but the fifth value which is 1

In [10]:
x=np.zeros(10) #1 create an array of values 
x[4]=1
print(x)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


# 2. Create a vector with values ranging from 10 to 49

In [14]:
a=np.arange(10,49)
print(a)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]


# 3.Create a 3x3 matrix with values ranging from 0 to 8

In [16]:
x =  np.arange(0, 9).reshape(3,3)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


# 4. Find indices of non-zero elements from [1,2,0,0,4,0]

In [19]:
n_array = np.array([1,2,0,0,4,0])
print(n_array)

res=np.nonzero(n_array)
print(res)

[1 2 0 0 4 0]
(array([0, 1, 4], dtype=int64),)


# 5.Create a 10x10 array with random values and find the minimum and maximum values.

In [23]:
x = np.random.random((10,10))
print("Original Array:")
print(x) 
xmin, xmax = x.min(), x.max()
print("Minimum and Maximum Values:")
print(xmin, xmax)

Original Array:
[[0.32734009 0.20735552 0.28034526 0.32286322 0.94507583 0.42252925
  0.85612499 0.71028561 0.01391703 0.52628996]
 [0.12751781 0.66431    0.06024482 0.57735117 0.08429717 0.81420188
  0.14857502 0.38070743 0.88724797 0.82697393]
 [0.08619985 0.75253305 0.12711615 0.09076933 0.88361306 0.60128408
  0.22800135 0.41292121 0.46405739 0.17348318]
 [0.91857028 0.25177695 0.20070406 0.81047553 0.4895252  0.69421787
  0.99797152 0.03919621 0.6380928  0.06820491]
 [0.42930107 0.4880208  0.87469374 0.87789349 0.25663269 0.2037155
  0.53434243 0.30925538 0.71361356 0.446205  ]
 [0.70633455 0.09622469 0.12863823 0.25918814 0.08212072 0.02823146
  0.1210782  0.14515234 0.92524323 0.96322525]
 [0.64326323 0.4583734  0.83564358 0.4609797  0.79403305 0.1304484
  0.25795786 0.71247015 0.5756807  0.20315648]
 [0.44779571 0.40698226 0.01897416 0.97334954 0.5232626  0.57664997
  0.58515711 0.46806057 0.91511447 0.10720103]
 [0.53492859 0.38773137 0.93640147 0.00220252 0.47712449 0.9729110

# 6. Create a random vector of size 30 and find the mean value.

In [29]:
a=np.random.random(30)
print(a)

print("The Mean Value is: ")
a.mean()

[0.55422198 0.08061146 0.23719522 0.72851879 0.50369603 0.90770285
 0.635608   0.28908422 0.98454587 0.759882   0.84554822 0.57935687
 0.86276793 0.55145229 0.13123728 0.30510044 0.38382442 0.395557
 0.98174819 0.67414029 0.15033387 0.80640235 0.48856464 0.78245053
 0.75095896 0.65796389 0.72706001 0.60794672 0.57544153 0.8219652 ]
The Mean Value is: 


0.5920295688840079